### ISSUE TITLE
Could we choose M106 and M107 also?

### ISSUE THREAD

**Issue by bywebberen** [arkypita/LaserGRBL#201] opened 2017-12-06 18:13 UTC
Hi there.

So I am new into ingraving. I have been 3D printing for a while, and I just built a Laser-Cutter/ingraver.

My setup runs on a standard Arduino ramps 1.4 setup and everything is working accordingly.

I would love to use GRBL for grayscale images on wood and stuff. But...
![2017-12-04 17 26 45](https://user-images.githubusercontent.com/34316149/33677586-9521b49e-dab9-11e7-91ac-b3a6a7dea3b2.jpg)
 I Fire my laser with M106 and shut it with M107 ??? Is there a WAY ?

**Comment by arkypita** [comment] 2017-12-06 18:19
duplicate of #191

**Closed by arkypita** 2017-12-06 18:19 UTC
